include $(FW_MAKEDIR)/common.mk

APPLICATION_NAME = Recapable
Recapable_FRAMEWORKS = CoreGraphics
Recapable_OBJC_FILES = Categories.m RCSelectOptionController.m RCTextFieldCell.m RCCreateViewController.m RCRootViewController.m RecapableAppDelegate.m main.m

include $(FW_MAKEDIR)/application.mk
